### ISSUE TITLE
Build and cache binary packages on Linux

### ISSUE THREAD

**Issue by krlmlr** [r-lib/crancache#20]
Would help revdep-checking on Linux, I think.

https://github.com/r-lib/revdepcheck/issues/45

**Comment by gaborcsardi** [comment]
I think it is happening already, but there is nothing in place to prevent binary incompatibilities....

**Comment by krlmlr** [comment]
Yes and no. The binary files in my local crancache don't contain any `.so` files.

**Comment by gaborcsardi** [comment]
Interesting. I'll investigate. (But you can, too. :)

**Comment by krlmlr** [comment]
Don't know where I looked yesterday.
