### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by krlmlr** [r-lib/crancache#31]
Is there an ETA? I'm thinking about using this for *tic* (https://github.com/ropenscilabs/tic/issues/35#issuecomment-361680021), but we'd also need a way to purge old versions from the cache.

**Comment by gaborcsardi** [comment]
`pkgdepends` has a better cache, and we might switch to that. `crancache` mimics the base R functions, and this makes it hacky and complex. The `pkgdepends` cache is way simpler, and much more stable.

**Comment by krlmlr** [comment]
Thanks!
