### ISSUE TITLE
Can't access https://install-github.me/r-lib/crancache

### ISSUE THREAD

**Issue by kenahoo** [r-lib/crancache#33]
The instructions in the README say to do `source("https://install-github.me/r-lib/crancache")`.  I wanted to look at what's behind that URL before running its code, but Chrome says the HTTPS certificate isn't valid, so it refused to load it.

I can override Chrome - but my company's firewall says it contains "malicious code" (sometimes it's overzealous...).

I *think* the certificate error may actually be caused by my firewall itself, which is decidedly unhelpful of it.

In any case - I tried going to the same URL in my phone (which isn't inside the firewall), and saw that the code at that URL is pretty large.  But is it basically just doing `devtools::install_github('r-lib/crancache')`?  Is that another reasonable option, if I've already got `devtools` (or `remotes`) installed?

**Comment by gaborcsardi** [comment]
> I think the certificate error may actually be caused by my firewall itself

Indeed this is the case, the certificate is valid.

> But is it basically just doing devtools::install_github('r-lib/crancache')? Is that another reasonable option, if I've already got devtools (or remotes) installed?

Sure, `remotes::install_github()` is fine.

**Comment by kenahoo** [comment]
Thanks.
