### ISSUE TITLE
update_cache_binaries(): length(x) = 2 > 1' in coercion to 'logical(1) ERROR

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/crancache#35]
In `update_cache_binaries()`, there's:

https://github.com/r-lib/crancache/blob/e2185c76b6fcd36c9970cfa22ffd2cb62b13eb53/R/binaries.R#L7-L8

That `grepl()` statement can resolve to a logical vector of any length.

I just ran into this indirectly (sorry, tried but fail to reproduce and don't have much time) where I ran with:
```
_R_CHECK_LENGTH_1_CONDITION=true
_R_CHECK_LENGTH_1_LOGIC2_=true
```
and received:
```r
...
Adding 'fs_1.3.0.tar.gz' to the cache
Error in "INSTALL_opts" %in% names(args) && grepl("--no-test-load", args$INSTALL_opts,  : 
  'length(x) = 2 > 1' in coercion to 'logical(1)'
Calls: <Anonymous> ... update_cache -> update_cache_safe -> update_cache_binaries
```

**Comment by jennybc** [comment]
I just hit this in a bookdown render workflow (which is neither here nor there).

**Comment by llrs** [comment]
I think this (and #45) is fixed in https://github.com/r-lib/crancache/commit/fc51e313db93780b1efd870f1b6bd3b638c909d3. Thanks again!
